### ISSUE TITLE
Simplifier should read the entire vertex, not just positions

### ISSUE THREAD

**Issue by gwihlidal** [gwihlidal/meshopt-rs#7]
Simplifier actually reads the entire vertex, not just position data - it has preferential treatment for position data in the vertex, but it uses other bytes to figure out where UV collapses happen.

It's not a major issue currently, but this should be addressed later (possibly with some interface changes on the C side to make things nicer in this area).

**Comment by zeux** [comment]
I lied :( The C interface is actually correct, and therefore the Rust version is also correct because it's the obvious code that you write for a C interface like this and it works :D

I confused myself - for some reason I had a vague memory of reading other vertex data to perform indexing, but upon closer inspection I remembered that the attribute seams are currently inferred from the input index stream. Only position data is read.

This might need to change long term as one of the big issues is that the simplifier currently can't distinguish normal seams from UV seams (and they are very different in terms of how they should be handled). However, this requires a different C-side interface anyway :)

So this issue can be closed.

**Comment by gwihlidal** [comment]
Sounds good!
